# question1

In [1]:
import numpy as np
import math

arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# question2

In [2]:
import numpy as np

a = []
b = []
lis = []
for i in range(5):
    n1 = int(input("Enter five numbers of the first list one by one: "))
    a.append(n1)
a1 = np.array(a)
print(a1)
a11 = np.sort(a1)
print(a11)
for i in range(5):
    n2 = int(input("Enter five numbers of the second list one by one: "))
    b.append(n2)
b1 = np.array(b)
print(b1)
b11 = np.sort(b1)
print(b11)
c1 = np.concatenate((a1,b1))
print(c1)
d1 = np.sort(c1)
print(d1)


Enter five numbers of the first list one by one: 1
Enter five numbers of the first list one by one: 2
Enter five numbers of the first list one by one: 3
Enter five numbers of the first list one by one: 4
Enter five numbers of the first list one by one: 5
[1 2 3 4 5]
[1 2 3 4 5]
Enter five numbers of the second list one by one: 6
Enter five numbers of the second list one by one: 73
Enter five numbers of the second list one by one: 5
Enter five numbers of the second list one by one: 2
Enter five numbers of the second list one by one: 11
[ 6 73  5  2 11]
[ 2  5  6 11 73]
[ 1  2  3  4  5  6 73  5  2 11]
[ 1  2  2  3  4  5  5  6 11 73]


# question3

In [3]:
import numpy as np
arr = np.random.rand(3,4)
print(arr)
print(np.shape(arr))
print(np.size(arr))
print(arr.ndim)

[[0.31828298 0.35881325 0.34156699 0.78863825]
 [0.96564442 0.44916086 0.32430722 0.10961114]
 [0.88854033 0.84011723 0.35965443 0.28468336]]
(3, 4)
12
2


# question4

In [4]:
import numpy as np 

arr = np.arange(1,10,2)
print(arr)
print(arr.ndim)
arr = np.expand_dims(arr, axis=1)
print(arr.ndim)
print(arr)

[1 3 5 7 9]
1
2
[[1]
 [3]
 [5]
 [7]
 [9]]


# question5

In [5]:
import numpy as np

a1 = np.random.rand(3,3)
b1 = np.random.rand(3,3)
print( "vstack example:\n",np.vstack((a1,b1)))
print("hstack example:\n", np.hstack((a1,b1)))

vstack example:
 [[0.5849683  0.37209201 0.76167171]
 [0.06325731 0.94013331 0.39994451]
 [0.99028021 0.94669198 0.93277855]
 [0.80484124 0.0765733  0.34046921]
 [0.66304925 0.42094258 0.20138604]
 [0.36074581 0.6542573  0.6392462 ]]
hstack example:
 [[0.5849683  0.37209201 0.76167171 0.80484124 0.0765733  0.34046921]
 [0.06325731 0.94013331 0.39994451 0.66304925 0.42094258 0.20138604]
 [0.99028021 0.94669198 0.93277855 0.36074581 0.6542573  0.6392462 ]]


# question6

In [6]:
import numpy as np 
a = np.array([1,2,3,4,5])
print(a[2])

b = np.array([[1,2,3,4],[6,7,8,9]])
print(b[1,0])


3
6
